# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e03e5f53111132b3524f608d174d6c551de165627737ff2fb901ad4e07a5768332110b304d102d4408cc171973c8abc9058d0feaa60cbf0e9b4a8b2a8a2748b

test:
  secret_key_base: ee300dfe1a7135ee84a936153880014b97b5d10fd02ab44c28982f3684b8149665d9aa42a7be95407d6dccf4e5edecd0ed0ce500f8bfa6babbd58c9c0ac9a4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
